### ISSUE TITLE
Snow Crash won't build with MinGW on Windows

### ISSUE THREAD

**Issue by alikh31** [apiaryio/snowcrash#118]
In case of changing the setting on [configure](https://github.com/apiaryio/snowcrash/blob/master/configure#L196) file in order to force GYP to build the `makefile` on windows and after that to compile the code using `minGW`, the produce library for snow crash does not working correctly.
It recognize the `BluePring` name and the rest of the `BluePrint` will be assume as the description.

CC. @zdne

**Comment by kylef** [comment]
Hi @alikh31,

Seems this has been open for some years now. Would you be able to elaborate on what problem you are having here (if it is still applicable, perhaps the problem has been fixed in later versions).

Would love to see some steps to reproduce/sample blueprint causing a problem.

Thanks!
