### ISSUE TITLE
Non-indented Body under Response in an action

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/snowcrash#148]
If you look [here](https://github.com/apiaryio/snowcrash/blob/84e18913994c3a0661ac0762ac7017fce76eab26/src/ActionParser.h#L119)

```
## GET /1

+ Response 200

+ Body

        {}
```

casually ignores the `Body` node and sets the `Response` body as empty.

We can improve this by adding the `Body`'s asset to `Response`.

**Comment by abtris** [comment]
Migrated to apiaryio/drafter#642
