### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by DataGreed** [apiaryio/snowcrash#259]
Hi! Does snowcrash have any kind of python bindings? Cannot find one :) I wanted to make python tests based  on the blueprint

by the way, how hard is it to create this bindings/wrappers by myself, where do I start?

Thanks

**Comment by zdne** [comment]
Snow Snake?! Oh my :dancer:

**Comment by kylef** [comment]
There is a Python 3 binding available at https://github.com/kylef/draughtsman .
