### ISSUE TITLE
Configure script requires python2

### ISSUE THREAD

**Issue by makkrnic** [apiaryio/snowcrash#261]
And I couldn't find it documented anywhere.
That presents a big problem specially when installing snowcrash as part of other packages e.g. redsnow or apiaryio gem because it fails silently and it seems that the installation has succeeded but there are missing libraries, like `libsnowcrash`

I believe sufficient fix would be replacing the first line in configure
`#!/usr/bin/env python`
with 
`#!/usr/bin/env python2`

**Comment by zdne** [comment]
@kylef can you please look into this?
