### ISSUE TITLE
Use libsos Xcode Project in snowcrash's Xcode workspace

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/snowcrash#274]
Depends on apiaryio/sos#3

**Comment by zdne** [comment]
@pksunkara what's up with this? If this is still issue please add some additional explanation what is this about (and labels).

**Comment by pksunkara** [comment]
Basically, we need to rebuild our Xcode workspace containing all our C++ repos.

**Comment by pksunkara** [comment]
Doesn't need this since `sos` moved to drafter.
