### ISSUE TITLE
Relation type with illegal character(s) is silently ignored

### ISSUE THREAD

**Issue by zdne** [apiaryio/snowcrash#320]
...and added as part of the description 

#### Blueprint

```markdown
## Retrieve the Entry Point [GET]
+ relation: a relation
```

another example: 

```markdown
### List all questions [GET]

+ Relation: Questions
```

Parser should spot this and warn about illegal characters in the relation type identifier

**Comment by pksunkara** [comment]
I think this should be fixed during [this](https://github.com/apiaryio/snowcrash/milestones/Keywords%20&%20Identifiers) milestone.

**Comment by zdne** [comment]
> I think this should be fixed along with the issues in this milestone.

@pksunkara note this should have been developed using the "loose" matching in the first place instead of relying on "it will be done properly later".

**Comment by zdne** [comment]
Related bug report: https://github.com/apiaryio/api-blueprint/issues/193
