### ISSUE TITLE
Crash while parsing malformed blueprint

### ISSUE THREAD

**Issue by zdne** [apiaryio/snowcrash#322]
Parsing following blueprint results in crash: 

```markdown
## GET /a

+ Response 200

            a
>           b
            e
# B
```

```
Assertion failed: (0), function src_map_location, file ../drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.c, line 158.
Abort trap: 6
```

Note:  The error is most likely caused in our `sundown` module, but due to lack of the test there it should be tested a tracked in Snow Crash.

**Comment by pksunkara** [comment]
Comment to check how github renders the above markdown.

## GET /a

+ Response 200

            a
>           b
            e
# B

**Comment by pksunkara** [comment]
@kylef Please make sure that our sundown fork parses the above blueprint similarly to how github parses it.

**Comment by zdne** [comment]
@pksunkara not sure what your comment is about – can you elaborate? For the record I do now want us to do any updates to our fork of sundown except stabilization (=fixing any crashes). So if you are asking for brining any new functionality that has been introduced in whatever-github-now-uses-since-sundown then the answer is no.

**Comment by pksunkara** [comment]
Okay. Can we have a test for this in markdown-parser?

Pavan Kumar Sunkara

**Comment by kylef** [comment]
I disagree that GitHub renders this correctly and it should instead be rendered as it is in the CommonMark specification:

![screen shot 2015-05-26 at 07 30 44](https://cloud.githubusercontent.com/assets/44164/7814775/30dd3540-0379-11e5-9312-ffd589fe8061.png)
