### ISSUE TITLE
Errors and warnings, wtf?

### ISSUE THREAD

**Issue by foxx** [apiaryio/snowcrash#325]
I'm trying to determine what the index/location means on the error output, as both never seem to relate to the actual error that has occurred, and the documentation doesn't explain this clearly. I would have expected line/col, or the ability to translate it to this (so the writer knows roughly where his error was).

Could someone take a moment to explain what these two values mean and how they should be interpreted? 

Thank you

**Comment by zdne** [comment]
Hey @foxx the numbers are ranges in the `:<character index>:<character count>` format. A warning can span across several non-continuous blocks. See https://github.com/apiaryio/snowcrash/issues/121#issuecomment-46945265 for details. 

Also are you using the Snow Crash library directly or through Drafter CLI? If the later there is the option to print it out in line - column format (check `drafter -h`).

Does this answer your question?

**Comment by foxx** [comment]
Thanks for the quick reply @zdne.

Now I understand, the char index/count is used to reference the start/end position of the block which caused an error, and this may have occurred across multiple lines. Also I didn't realise that Drafter could output in line/col format, so that has solved my problem :)

**Comment by zdne** [comment]
Thanks @foxx ! This is a great input on usability / documentation – I have added https://github.com/apiaryio/snowcrash/wiki/Source-Maps to help others understanding the source map numbers in a future!
