### ISSUE TITLE
Incorrect handling of `-` in attribute value 

### ISSUE THREAD

**Issue by w-vi** [apiaryio/snowcrash#326]
It appears as though escape characters may not be working within the example value of an attribute in the `+ Attributes` section. For example:

```md
FORMAT: 1A

# Escaping

# API Root [/]


## Retrieve the Entry Point [GET]

+ Response 200 (application/json)
    
    + Attributes (object)
    
        + authenticationToken: 6ce40b88\-d366\-4c5d\-b60d\-cfbd9107bcd9 (string, required) - The token that should be sent in the X\-Auth\-Token request header on subsequent requests to the API that require authentication.
        + id: 6 (number, required) - if of the thing


```

Terminates the example after the 6ce40b88\- even though the hyphen is escaped. If it is not escaped it doesn't work either.

**Comment by zdne** [comment]
@w-vi those are not mentioned to escape characters (since we are in Markdown) – use back tick instead – see https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords

```
authenticationToken: `6ce40b88-d366-4c5d-b60d-cfbd9107bcd9`
```

**Comment by w-vi** [comment]
@zdne Cheers switching between languages and different syntaxes doesn't really help.

**Comment by w-vi** [comment]
So closing this one as it solves my problem.
