### ISSUE TITLE
Warn on method names that are not uppercase

### ISSUE THREAD

**Issue by Almad** [apiaryio/snowcrash#334]
Warnings are confusing if method name is not written all-CAPS and therefore not recognised.

Snowcrash should recognise the line (be case-insensitive) and issue a warning.

Fore more details, [see this SO question](https://stackoverflow.com/questions/30474331/apiary-ignoring-unrecognized-block/30478818#30478818)

**Comment by zdne** [comment]
To be handled in https://github.com/apiaryio/snowcrash/milestones/Keywords%20&%20Identifiers

**Comment by abtris** [comment]
Migrated to apiaryio/drafter#635
