### ISSUE TITLE
MSON Named Types - parsed as variable

### ISSUE THREAD

**Issue by klokane** [apiaryio/snowcrash#335]
Following MSON Named type
```md
## *User (object)*
- m1
```

is parsed as variable:
```js
...
    "element": "dataStructure",
          "name": {
            "literal": "User (object)",
            "variable": true
          },
...
```

according to discussion with @zdne it is bug

**Comment by zdne** [comment]
Yes, this is actually incorrect and meaningless syntax

**Comment by pksunkara** [comment]
@zdne What should be the actual parsing result? Parsing it as just markdown?

**Comment by zdne** [comment]
@pksunkara that would work, however, if possible and to too complex it may be better to nudge user that he probably wanted to say something else. ...

**Comment by pksunkara** [comment]
Expected is:

```
...
    "element": "dataStructure",
          "name": {
            "literal": "User (object)",
            "variable": false
          },
...

```

**Comment by pksunkara** [comment]
Actually, the following MSON is valid:

```apib
## *User*
- m1
```

and it should give the following refract:

```json
"name": {
  "literal": "User",
  "variable": true
},
```

The issue with the given blueprint is that `(` and other reserved characters are not allowed in named type names. Therefore we should provide a warning along with setting `variable: false`.
