### ISSUE TITLE
MSON value - parsing number

### ISSUE THREAD

**Issue by klokane** [apiaryio/snowcrash#338]
Negative numbers in value are not parsed:

For following blueprint
```md
# <API name>
<API description>

# Data Structures

## Customer (object)
- id: -1 (number) - unique number
```

You will obtain warning:
```
warning: (6)  no value(s) specified :74:32
```

and everything after minus sign is parsed as description:
```
 "description": "1 (number) - unique number",
```

**Comment by kylef** [comment]
@klokane I don't believe this is a bug, but instead expected behaviour. `-` is a reserved character and must be escaped.

You should instead us it like so:

```
- id: `-1` (number) - unique number
```

**Comment by pksunkara** [comment]
Yup. Not a bug as @kylef said.

**Comment by klokane** [comment]
At least I propose different warning. As user there have no idea what happens.
Especcily in case while mson with plus sign os parsed correctly
```
- theNumber: +1 (number) - this will be parsed without problem
```

It is not problem to check if first character in message and say to user "looks like negative number, please use escaping"

**Comment by pksunkara** [comment]
@klokane Yes, we have already created an issue for that. Refer here, https://github.com/apiaryio/api-blueprint/issues/210

**Comment by klokane** [comment]
@pksunkara ok, thank. I miss this
