### ISSUE TITLE
Snowcrash should detect identifiers with disallowed characters and warn

### ISSUE THREAD

**Issue by kylef** [apiaryio/snowcrash#340]
Take the following blueprint:

```apib
## Test Resource [/test]
### Testing action (foo) [GET]

adfsdf
```

This will result in a single resource without any actions. The action is silently treated as the description because it is using characters not permitted in the identifier.

```json
{
  "element": "resource",
  "name": "Test Resource",
  "description": "### Testing action (foo) [GET]\n\nadfsdf"
}
```

I think instead, we should detect the [GET] and understand the user probably wants this to be an action. In this case throw a warning that the action name is using the reserved characters `(` and `)`.

**Comment by zdne** [comment]
I believe this should be covered by the issues of this milestone https://github.com/apiaryio/snowcrash/milestones/Keywords%20&%20Identifiers , can you confirm?

**Comment by kylef** [comment]
Yes, this is a dupe of #41.
