### ISSUE TITLE
Resource section identifier can not start with a forward slash

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/snowcrash#341]
As reported in danielgtaylor/aglio#94. This seems like something that the parser should probably support.

Related to this, it also generates kind of a weird warning:

```
>> Line 58: The URI template contains square brackets, please percent encode square brackets as %5B and %5D (warning code 12)
```

**Comment by zdne** [comment]
This is the limitation of the current spec. 

> An identifier is any non-empty combination of any character except [, ], (, ) and newline characters.
> An identifier must not contain any of the keywords.

where URI templates are considered being a keyword 

See https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-keywords

If you really think it should be possible having an identifier starting with `/` or being an URI temple please open the discussion on API Blueprint issues.
