### ISSUE TITLE
Add nullable type attribute

### ISSUE THREAD

**Issue by obihann** [apiaryio/snowcrash#347]
Based on apiaryio/mson#38 the `nullable` type attribute should be added. Examples of used and rendering can be found in the pull request.

**Comment by obihann** [comment]
Diving into this now, would it be possible to get in contact with the team via gchat / slack / whatever so that I can ask questions if necessary on this and other pull requests without needing to make huge comment trails?

**Comment by pksunkara** [comment]
We will be online in https://gitter.im/apiaryio/api-blueprint
