### ISSUE TITLE
URI Parameters - AST output does not provide info about `enum` type 

### ISSUE THREAD

**Issue by klokane** [apiaryio/snowcrash#356]
Following Blueprint

```
FORMAT: 1A
​
# Polls API Root [/]
​
## Questions collection [/questions{?page}]
​
+ Parameters
    + page (optional, enum[number]) ... The page of questions to return
        + Default: `2`, `3`
        
        + Members
            + 1
            + 2
            + 3
```

create following AST (jus parameter related part):
```
        "parameters": [
              {
                "name": "page",
                "description": "",
                "type": "number",
                "required": false,
                "default": "2",
                "example": "",
                "values": [
                  {
                    "value": "1"
                  },
                  {
                    "value": "2"
                  },
                  {
                    "value": "3"
                  }
                ]
              }
```

There is missing info about `enum` definition. Instead it expose definition of internal type. 

Same output is created for `+ page (optional, number) `. Related to #355 

AST definition is not clear about correct output https://github.com/apiaryio/api-blueprint-ast#parameter-object

**Comment by pksunkara** [comment]
Parameter object in API Blueprint AST doesn't need any information about `enum` specifically. If it contains non-empty `values`, we can assume it's an `enum`.

**Comment by klokane** [comment]
this dispute was opened by @XVincentX - is it resolved by your opinion?

**Comment by pksunkara** [comment]
To add another point, `enum` is introduced only in MSON. There is nothing like that in old parameter syntax.
