### ISSUE TITLE
Style matters, style is everything!

### ISSUE THREAD

**Issue by w-vi** [apiaryio/snowcrash#360]
Proposal of a clang-format style definition for all the C++ tools and libs in the API Blueprint ecosystem.
To make it easier for everybody, no more whitespace or whatever style discussions. Give it a try, see if you like it and propose changes.

https://gist.github.com/w-vi/bad74be461b3181f24e1

**Comment by w-vi** [comment]
@pksunkara  have had a chance to look at it?

**Comment by pksunkara** [comment]
* `AlwaysBreakBeforeMultilineStrings` should probably be `true`
* `BinPackArguments` and `BinPackParameters` should probably be `false`
* `SpaceAfterCStyleCast` should be `true`. Better readability

@w-vi Done.

**Comment by w-vi** [comment]
Agree with all but `SpaceAftertCStyleCast`.

`(void*)pObj` looks to me more clear than  `(void *) pObj` 

what others like @klokane think? I'll accept it both ways but let the majority decide

**Comment by klokane** [comment]
Agree with @w-vi casting with space is feeling "loose context"
Additionaly it should not be used in C++ much better and clear is use casting operators

**Comment by pksunkara** [comment]
Okay. Let's do this.

**Comment by w-vi** [comment]
Gist updated

**Comment by kylef** [comment]
This has been completed in https://github.com/apiaryio/snowcrash/pull/380.
