### ISSUE TITLE
error: (4)  nested complex types are not implemented

### ISSUE THREAD

**Issue by reactormonk** [apiaryio/snowcrash#363]
Happens with

    FORMAT: 1A
    HOST: https://foo.com/api/3.0

    # API Root [/]

    ## Foo [/foo]

    ### Request [GET /foo]

    + Response 200 (application/json)
        + Attributes
            + chart (object, required)
                + series (array[object], required)
                    + one: `text` ([string, number, boolean, date], optional)

**Comment by zdne** [comment]
`one: `text` ([string, number, boolean, date], optional)` do you want to say the property "one" is an enum of those four types? 

If so it should be:

```
- one: `text` (enum[string, number, boolean, date], optional)
```

or 

```

- one (enum, optional)
	- text (string)
	- (number)
	- (boolean)
	- (date)
```

**Comment by Matt-Jensen** [comment]
Thanks for those examples. I may be under some misapprehension, however I was under the impression that enum was to be used when properties have a known list values?

If we assume property "one" has unknown values of many different types how would it be declared?

**Comment by zdne** [comment]
> however I was under the impression that enum was to be used when properties have a known list values?

Enum is an enumeration of [Value Definitions](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#34-value-definition). These definitions do not have a (sample) value specified a Type Definition is enough.

> If we assume property "one" has unknown values of many different types how would it be declared?

Generics are currently not well scoped out in the spec and definitely not implemented in the parser. 

See [Generic Named Type](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#311-generic-named-declaration) (again this is not implemented AFAIK). 

For now, can you work around without the generics?

**Comment by Matt-Jensen** [comment]
I think the semantics of my previous comment were a bit off.  What we were looking to do is [already described by the MSON spec](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#43-nested-member-types).
```
- colors (enum)
    - *red* (string)
    - *5* (number)
```
Using _Enum Structures_ with _Variable Values_ in _Nested Member Types_. I have parsed use case successfully just to be sure, so I believe we can close this issue.  Thank you for your help!
