### ISSUE TITLE
MSON example string value end up as enum in json schema

### ISSUE THREAD

**Issue by maciejmrowiec** [apiaryio/snowcrash#374]
There seem to be an issue with **example values** where it ends up as enum field in json schema.

```
+ Response 200 (application/json)
    + Attributes (array, fixed)
        + attribute (object)
            + id: `00a0c91e6-7dec-11d0-a765-f81d4faebf6` (string) - id
```

I end up with json schema (in apiary):

```
{
  "type": "array",
  "items": [
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "enum": [
            "00a0c91e6-7dec-11d0-a765-f81d4faebf6"
          ],
          "description": "id"
        }
      },
      "required": [
        "id"
      ]
    }
  ],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Comment by kylef** [comment]
@maciejmrowiec I believe this is expected behaviour. Since you've used the `fixed` keyword on the attributes. Fixed means that the values are fixed.

/cc @w-vi

**Comment by maciejmrowiec** [comment]
@kylef I thought `fixed` works as trigger for apiary to use experimental bug fixes for array support.

**Comment by kylef** [comment]
No, both fixed and non-fixed **should** work as they are described in the [MSON Specification](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md).

I'd say there is an oversight in the MSON Language which prevents you describing data structures which don't fit into fixed/non-fixed and I'd love to reconsider how these work or introduce new functionality into MSON.

**Comment by kylef** [comment]
I think what you are looking for is to describe an array of a certain type without fixed values. I've created https://github.com/apiaryio/mson/issues/66 to track this missing functionality.
