### ISSUE TITLE
‘auto_ptr’ is deprecated and will be removed from C++17

### ISSUE THREAD

**Issue by LinusU** [apiaryio/snowcrash#385]
‘auto_ptr’ is deprecated and should be replaced with `std::unique_ptr` or `std::shared_ptr`. Not only will `std::auto_ptr` be removed from the C++ standard soon, it spits out _a lot_ of warnings when compiling.

e.g.
```text
In file included from ../drafter/ext/snowcrash/src/MSONSourcemap.cc:9:0:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
```

**Comment by kylef** [comment]
Currently Snowcrash, Drafter and Protagonist doesn't yet depend on C++11. `auto_ptr` was only deprecated in C++11.

We have plans to deprecate older compiler support in Snowcrash, Drafter and Protagonist (https://github.com/apiaryio/drafter/issues/262) which will allow us to start making use of some C++11 features, including `auto_ptr`.

This is very planned in the future.

**Comment by kylef** [comment]
This has been completed in #390.
