### ISSUE TITLE
Error parsing snake_case attribute content

### ISSUE THREAD

**Issue by OscarSwanros** [apiaryio/snowcrash#432]
I'm trying to express the following response using response attributes:

```json
{
  "status": "error",
  "error_message": "content_cant_be_blank"
}
```

And I'm trying to do this like so:

![img](https://cl.ly/2K3r1h1C0l1k/Image%202017-07-08%20at%2012.40.13%20PM.png)

But the parser somehow thinks that the camel_case content of this is part of the name.

**Comment by kylef** [comment]
`_` is a [reserved character](https://apiblueprint.org/documentation/mson/specification.html#6-reserved-characters--keywords) and thus it must be escaped.

This can be achieved via the following:

```apib
+ Response 422 (application/json)
    + Attributes
        + status: error
        + `error_message`: `content_cant_be_blank`
```
