### ISSUE TITLE
Wrong test data for Resource groups

### ISSUE THREAD

**Issue by goganchic** [apiaryio/snowcrash#438]
Recently I've found such test https://github.com/apiaryio/snowcrash/blob/master/test/test-ResourceGroupParser.cc#L103-L133

It tries to process such apib with resource group parser:
```apib
# Group
## /r1
p1
## /r2
p2
```

This data will not match [resource group regexp](https://github.com/apiaryio/snowcrash/blob/master/src/ResourceGroupParser.h#L19) which requires some name after "Group" keyword.

I think this test is wrong and should be modified or removed. It is not possible to have anonymous groups now.

**Comment by abtris** [comment]
Migrated to apiaryio/drafter#629
