### ISSUE TITLE
Drafter - snowcrash parser harness

### ISSUE THREAD

**Issue by ecordell** [apiaryio/snowcrash#57]
In the interest of keeping documentation up-to-date, it seems you would want to get warnings when your example Body doesn't fit your Schema.

Maybe this issue should be for a different project...it's definitely something snowcrash could handle, but perhaps it shouldn't have a dependency on json schema?

**Comment by zdne** [comment]
We have kicked-off the Drafter project. Initially it will provide expansion of MSON data structures (types) and rendering of representations out of it. Support for additional features is in the pipeline. 

If needed please continue with this discussion at https://github.com/apiaryio/drafter/issues/31

**Comment by ecordell** [comment]
@zdne Looks great! Can't wait to see what happens. If I manage to find some time I'd love to contribute.

**Comment by zdne** [comment]
Thanks @ecordell ! At the moment it is just a simple wrapper but the real juice is coming soon!
