### ISSUE TITLE
Escape Unsafe Characters in URI Templates

### ISSUE THREAD

**Issue by zdne** [apiaryio/snowcrash#61]
In relation to #58 the parser should %-escape any potentially unsafe characters in resource URI template.

**Comment by ryannealmes** [comment]
Is this issue going to be addressed ever? It seems to have been open for quite a while. ANy feedback on this?

**Comment by kylef** [comment]
> Well, that is the point of this issue. Parser will warn & offer the suggestion to pct-encode an illegal character..

This has been done:

```apib
FORMAT: 1A

# Resource [/something{?a-b}]

+ Parameters
    + `a-b`

```

Produces:

> warning: (12)  URI template expression "?a-b" contains hyphens. Allowed characters for expressions are A-Z a-z 0-9 _ and percent encoded characters
